### ISSUE TITLE
Updated CRX file for the MSN Shopping Script alone

### ISSUE THREAD

**Issue by Chappie18** [RoNzzzz/BIngSearcher#4] opened 2023-06-22 05:00 UTC
May I have a crx file for MSN Shopping Script with auto executing task on shopping page without any click? I believe it will be a useful feature.

**Comment by RohanPhuyal** [comment] 2023-06-22 14:16
> May I have a crx file for MSN Shopping Script with auto executing task on shopping page without any click? I believe it will be a useful feature.

Maybe you can use Bookmarklet? 
Is it ok for you to use Bookmarklet?

**Comment by RohanPhuyal** [comment] 2023-06-22 14:45
[AutoScriptExecution.zip](https://github.com/RoNzzzz/BIngSearcher/files/11835201/AutoScriptExecution.zip)

crx may not work as it can't be used (This extension is not from any known source, and may have been added without your knowledge.)

use above zip and comment if the issue is solved so I can close it

**Comment by Chappie18** [comment] 2023-06-23 03:08
First and foremost, thank you for responding quickly and providing a solution.
It initially worked and selected the correct option, but no points were recorded. So I had to refresh the website twice before it began registering points. As a result, I feel this functionality will aid in fixing such issues:
- Adding a page refresh timer every 10 seconds
- It would also be great if the script stopped after a set amount of time, say 30 seconds.

**Comment by RohanPhuyal** [comment] 2023-06-23 03:10
> First and foremost, thank you for responding quickly and providing a solution. It initially worked and selected the correct option, but no points were recorded. So I had to refresh the website twice before it began registering points. As a result, I feel this functionality will aid in fixing such issues:
> 
> * Adding a page refresh timer every 10 seconds
> * It would also be great if the script stopped after a set amount of time, say 30 seconds.

Ok, I am about to head off right now, will do it when I get back home :)

**Comment by RohanPhuyal** [comment] 2023-06-24 07:18
[AutoScriptExecution.zip](https://github.com/RoNzzzz/BIngSearcher/files/11855837/AutoScriptExecution.zip)

Here It does what you said (lil buggy and not much optimized)

**Closed as completed by RohanPhuyal** 2023-06-24 07:18 UTC

**Comment by Chappie18** [comment] 2023-06-24 07:19
Thank you

**Comment by Chappie18** [comment] 2023-06-26 13:20
I'm not sure whether this is too much to ask considering that you already given me the auto-msn shopping extension, but if you have a moment, would you mind sending me the updated zip file for the **MSN shopping** auto extension?

**Comment by RohanPhuyal** [comment] 2023-06-27 02:09
> I'm not sure whether this is too much to ask considering that you already given me the auto-msn shopping extension, but if you have a moment, would you mind sending me the updated zip file for the **MSN shopping** auto extension?


[AutoScriptExecution.zip](https://github.com/RoNzzzz/BIngSearcher/files/11876952/AutoScriptExecution.zip)
Test them, as I haven't tested them effectively

**Comment by Chappie18** [comment] 2023-08-03 12:35
Hey, it appears that the MSN Shopping Game patch wave is complete; could you maybe provide me with the updated auto msn shopping extension with an 11-second gap!
